version: "3.3"

networks:
  app-network:
    driver: bridge

services:

  server:
    image: adminko/test:backend
    command: /root/server
    ports:
      - "3000:3000"
    networks:
      - app-network

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php8.1.ini:/usr/local/etc/php/php.ini
      - ../:/var/www
    restart: always
    depends_on:
      - percona
    networks:
      - app-network

  percona:
    image: percona:8.0
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_DATABASE=backend-test
      - MYSQL_USER=backend-test
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/percona:/var/lib/mysql
      - ./logs/mysql/:/var/log/mysql1
    ports:
      - "3307:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - app-network
